/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostRouteImport } from './routes/host'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as ProfileUserSlugIndividualsRouteImport } from './routes/profile_.$userSlug.individuals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserSlugIndividualsRoute =
  ProfileUserSlugIndividualsRouteImport.update({
    id: '/profile_/$userSlug/individuals',
    path: '/profile/$userSlug/individuals',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/simulate': typeof SimulateRoute
  '/profile/$userSlug/individuals': typeof ProfileUserSlugIndividualsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/simulate': typeof SimulateRoute
  '/profile/$userSlug/individuals': typeof ProfileUserSlugIndividualsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/simulate': typeof SimulateRoute
  '/profile_/$userSlug/individuals': typeof ProfileUserSlugIndividualsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/lobby'
    | '/profile'
    | '/simulate'
    | '/profile/$userSlug/individuals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/host'
    | '/lobby'
    | '/profile'
    | '/simulate'
    | '/profile/$userSlug/individuals'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/lobby'
    | '/profile'
    | '/simulate'
    | '/profile_/$userSlug/individuals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRoute
  LobbyRoute: typeof LobbyRoute
  ProfileRoute: typeof ProfileRoute
  SimulateRoute: typeof SimulateRoute
  ProfileUserSlugIndividualsRoute: typeof ProfileUserSlugIndividualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/$userSlug/individuals': {
      id: '/profile_/$userSlug/individuals'
      path: '/profile/$userSlug/individuals'
      fullPath: '/profile/$userSlug/individuals'
      preLoaderRoute: typeof ProfileUserSlugIndividualsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRoute,
  LobbyRoute: LobbyRoute,
  ProfileRoute: ProfileRoute,
  SimulateRoute: SimulateRoute,
  ProfileUserSlugIndividualsRoute: ProfileUserSlugIndividualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
